-- task1
SELECT surname, job FROM EMPLOYEES
WHERE DEPT_ID = (SELECT DEPT_ID FROM EMPLOYEES
WHERE surname = 'Johnson') AND surname != 'Johnson'
ORDER BY 1;

-- task2
SELECT e.surname, e.job, d.dept_name FROM EMPLOYEES e
INNER JOIN DEPARTMENTS d ON e.DEPT_ID = d.DEPT_ID
WHERE e.DEPT_ID = (SELECT DEPT_ID FROM EMPLOYEES
WHERE surname = 'Johnson') AND surname != 'Johnson'
ORDER BY 1;

-- task3
SELECT surname, job, TO_CHAR(hire_date, 'YYYY-MM-DD') AS hire_date FROM EMPLOYEES
WHERE TO_CHAR(hire_date, 'YYYY-MM-DD') = (SELECT MIN(TO_CHAR(hire_date, 'YYYY-MM-DD')) FROM EMPLOYEES
WHERE job='LECTURER' )
AND job='LECTURER';

-- task4
SELECT DEPT_NAME AS department, surname, hire_date FROM EMPLOYEES 
JOIN DEPARTMENTS USING (dept_id) 
WHERE (dept_id, hire_date) IN (SELECT dept_id, MAX(hire_date) FROM EMPLOYEES GROUP BY dept_id)
ORDER BY 1;

-- task5
SELECT dept_id, dept_name, address FROM DEPARTMENTS
WHERE dept_id NOT IN (SELECT dept_id FROM EMPLOYEES WHERE dept_id IS NOT NULL);

-- task6
SELECT surname, job, salary FROM EMPLOYEES
WHERE job = 'PROFESSOR' AND EMP_ID NOT IN (SELECT boss_id FROM EMPLOYEES
WHERE job = 'PHD STUDENT') ;

-- task7
SELECT dept_name, COUNT(emp_id) as NUM_OF_EMPL
FROM EMPLOYEES INNER JOIN DEPARTMENTS USING (DEPT_ID)
GROUP BY DEPT_NAME
HAVING COUNT(EMP_ID) > (SELECT COUNT(EMP_ID) FROM EMPLOYEES INNER JOIN DEPARTMENTS USING (DEPT_ID)
WHERE DEPT_NAME = 'ADMINISTRATION'
GROUP BY DEPT_NAME)

-- task8
SELECT TO_CHAR(hire_date, 'YYYY') AS YEAR, count(emp_id) AS NUMBER_OF_PROFESSORS FROM EMPLOYEES
WHERE JOB = 'PROFESSOR'
GROUP BY TO_CHAR(hire_date, 'YYYY')
HAVING COUNT(emp_id) = (SELECT MAX(COUNT(emp_id))
FROM EMPLOYEES
WHERE JOB='PROFESSOR'
GROUP BY TO_CHAR(hire_date, 'YYYY'))
ORDER BY 1;

-- task9
SELECT DEPT_NAME AS DEPARTMENT, SUM(SALARY+COALESCE(ADD_SALARY, 0)) AS MAX_SUM
FROM EMPLOYEES INNER JOIN DEPARTMENTS USING (DEPT_ID)
GROUP BY DEPT_NAME
HAVING SUM(SALARY+COALESCE(ADD_SALARY, 0)) = (SELECT MAX(SUM(SALARY+COALESCE(ADD_SALARY, 0)))
FROM EMPLOYEES INNER JOIN DEPARTMENTS USING (DEPT_ID)
GROUP BY DEPT_NAME);